// Generated by Wrangler on Fri May 10 2024 20:37:28 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

export interface Env {
	GITHUB_ACCOUNT: string;
	GITHUB_REPO: string;
	GITHUB_TOKEN?: string;
}
